### ISSUE TITLE
特定のログインフローでセッション登録時にエラーが出る

### ISSUE THREAD

**Issue by jacopen** [cloudopsdays/dreamkast#84]
たとえば、未ログイン状態で
https://dreamkast-dk-72.dev.cloudnativedays.jp/codt2021/timetables

から、右上のログインを押し、その後セッションポチポチして最後に登録を押すとInternal server errorが出る

**Comment by jacopen** [comment]
```
I, [2021-07-13T03:25:16.212431 #11]  INFO -- omniauth: (auth0) Request phase initiated.
I, [2021-07-13T03:25:27.961920 #11]  INFO -- omniauth: (auth0) Callback phase initiated.
E, [2021-07-13T03:26:02.074450 #11] ERROR -- : [1ce7e03d-c7a8-4c04-843d-ec713be09355] Rendering 500 with exception: undefined method `avatar_or_dummy_url' for nil:NilClass
E, [2021-07-13T03:26:02.074599 #11] ERROR -- : [1ce7e03d-c7a8-4c04-843d-ec713be09355] /app/app/views/tracks/waiting.html.erb:61:in `block in _app_views_tracks_waiting_html_erb___4286571013282235301_50780'
/usr/local/bundle/gems/activerecord-6.0.3.1/lib/active_record/relation/delegation.rb:87:in `each'
/usr/local/bundle/gems/activerecord-6.0.3.1/lib/active_record/relation/delegation.rb:87:in `each'
/app/app/views/tracks/waiting.html.erb:56:in `_app_views_tracks_waiting_html_erb___4286571013282235301_50780'
/usr/local/bundle/gems/actionview-6.0.3.1/lib/action_view/base.rb:274:in `_run'
/usr/local/bundle/gems/actionview-6.0.3.1/lib/action_view/template.rb:185:in `block in render'
/usr/local/bundle/gems/activesupport-6.0.3.1/lib/active_support/notifications.rb:182:in `instrument'
/usr/local/bundle/gems/actionview-6.0.3.1/lib/action_view/template.rb:385:in `instrument_render_template'
/usr/local/bundle/gems/actionview-6.0.3.1/lib/action_view/template.rb:183:in `render'
/usr/local/bundle/gems/actionview-6.0.3.1/lib/action_view/renderer/template_renderer.rb:58:in `block (2 levels) in render_template'
/usr/local/bundle/gems/actionview-6.0.3.1/lib/action_view/renderer/abstract_renderer.rb:88:in `block in instrument'
/usr/local/bundle/gems/activesupport-6.0.3.1/lib/active_support/notifications.rb:180:in `block in instrument'
/usr/local/bundle/gems/activesupport-6.0.3.1/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/usr/local/bundle/gems/activesupport-6.0.3.1/lib/active_support/notifications.rb:180:in `instrument'
/usr/local/bundle/gems/actionview-6.0.3.1/lib/action_view/renderer/abstract_renderer.rb:87:in `instrument'
/usr/local/bundle/gems/actionview-6.0.3.1/lib/action_view/renderer/template_renderer.rb:57:in `block in render_template'
/usr/local/bundle/gems/actionview-6.0.3.1/lib/action_view/renderer/template_renderer.rb:65:in `render_with_layout'
/usr/local/bundle/gems/actionview-6.0.3.1/lib/action_view/renderer/template_renderer.rb:56:in `render_template'
/usr/local/bundle/gems/actionview-6.0.3.1/lib/action_view/renderer/template_renderer.rb:13:in `render'
/usr/local/bundle/gems/actionview-6.0.3.1/lib/action_view/renderer/renderer.rb:61:in `render_template_to_object'
/usr/local/bundle/gems/actionview-6.0.3.1/lib/action_view/renderer/renderer.rb:29:in `render_to_object'
/usr/local/bundle/gems/actionview-6.0.3.1/lib/action_view/rendering.rb:117:in `block in _render_template'
/usr/local/bundle/gems/actionview-6.0.3.1/lib/action_view/base.rb:304:in `in_rendering_context'
/usr/local/bundle/gems/actionview-6.0.3.1/lib/action_view/rendering.rb:116:in `_render_template'
/usr/local/bundle/gems/actionpack-6.0.3.1/lib/action_controller/metal/streaming.rb:218:in `_render_template'
/usr/local/bundle/gems/actionview-6.0.3.1/lib/action_view/rendering.rb:103:in `render_to_body'
/usr/local/bundle/gems/actionpack-6.0.3.1/lib/action_controller/metal/rendering.rb:52:in `render_to_body'
/usr/local/bundle/gems/actionpack-6.0.3.1/lib/action_controller/metal/renderers.rb:142:in `render_to_body'
/usr/local/bundle/gems/actionpack-6.0.3.1/lib/abstract_controller/rendering.rb:25:in `render'
/usr/local/bundle/gems/actionpack-6.0.3.1/lib/action_controller/metal/rendering.rb:36:in `render'
/usr/local/bundle/gems/actionpack-6.0.3.1/lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
/usr/local/bundle/gems/activesupport-6.0.3.1/lib/active_support/core_ext/benchmark.rb:14:in `block in ms'
/usr/local/lib/ruby/2.7.0/benchmark.rb:308:in `realtime'
/usr/local/bundle/gems/activesupport-6.0.3.1/lib/active_support/core_ext/benchmark.rb:14:in `ms'
/usr/local/bundle/gems/actionpack-6.0.3.1/lib/action_controller/metal/instrumentation.rb:44:in `block in render'
/usr/local/bundle/gems/actionpack-6.0.3.1/lib/action_controller/metal/instrumentation.rb:84:in `cleanup_view_runtime'
/usr/local/bundle/gems/activerecord-6.0.3.1/lib/active_record/railties/controller_runtime.rb:39:in `cleanup_view_runtime'
/usr/local/bundle/gems/actionpack-6.0.3.1/lib/action_controller/metal/instrumentation.rb:43:in `render'
/usr/local/bundle/gems/actionpack-6.0.3.1/lib/action_controller/metal/implicit_render.rb:35:in `default_render'
/usr/local/bundle/gems/actionpack-6.0.3.1/lib/action_controller/metal/basic_implicit_render.rb:6:in `block in send_action'
/usr/local/bundle/gems/actionpack-6.0.3.1/lib/action_controller/metal/basic_implicit_render.rb:6:in `tap'
/usr/local/bundle/gems/actionpack-6.0.3.1/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
/usr/local/bundle/gems/actionpack-6.0.3.1/lib/abstract_controller/base.rb:195:in `process_action'
/usr/local/bundle/gems/actionpack-6.0.3.1/lib/action_controller/metal/rendering.rb:30:in `process_action'
/usr/local/bundle/gems/actionpack-6.0.3.1/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
/usr/local/bundle/gems/activesupport-6.0.3.1/lib/active_support/callbacks.rb:112:in `block in run_callbacks'
/usr/local/bundle/gems/sentry-raven-3.0.0/lib/raven/integrations/rails/controller_transaction.rb:7:in `block in included'
/usr/local/bundle/gems/activesupport-6.0.3.1/lib/active_support/callbacks.rb:121:in `instance_exec'
/usr/local/bundle/gems/activesupport-6.0.3.1/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
/usr/local/bundle/gems/activesupport-6.0.3.1/lib/active_support/callbacks.rb:139:in `run_callbacks'
/usr/local/bundle/gems/actionpack-6.0.3.1/lib/abstract_controller/callbacks.rb:41:in `process_action'
/usr/local/bundle/gems/actionpack-6.0.3.1/lib/action_controller/metal/rescue.rb:22:in `process_action'
/usr/local/bundle/gems/actionpack-6.0.3.1/lib/action_controller/metal/instrumentation.rb:33:in `block in process_action'
/usr/local/bundle/gems/activesupport-6.0.3.1/lib/active_support/notifications.rb:180:in `block in instrument'
/usr/local/bundle/gems/activesupport-6.0.3.1/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/usr/local/bundle/gems/activesupport-6.0.3.1/lib/active_support/notifications.rb:180:in `instrument'
/usr/local/bundle/gems/actionpack-6.0.3.1/lib/action_controller/metal/instrumentation.rb:32:in `process_action'
/usr/local/bundle/gems/actionpack-6.0.3.1/lib/action_controller/metal/params_wrapper.rb:245:in `process_action'
/usr/local/bundle/gems/activerecord-6.0.3.1/lib/active_record/railties/controller_runtime.rb:27:in `process_action'
/usr/local/bundle/gems/actionpack-6.0.3.1/lib/abstract_controller/base.rb:136:in `process'
/usr/local/bundle/gems/actionview-6.0.3.1/lib/action_view/rendering.rb:39:in `process'
/usr/local/bundle/gems/actionpack-6.0.3.1/lib/action_controller/metal.rb:190:in `dispatch'
/usr/local/bundle/gems/actionpack-6.0.3.1/lib/action_controller/metal.rb:254:in `dispatch'
/usr/local/bundle/gems/actionpack-6.0.3.1/lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
/usr/local/bundle/gems/actionpack-6.0.3.1/lib/action_dispatch/routing/route_set.rb:33:in `serve'
/usr/local/bundle/gems/actionpack-6.0.3.1/lib/action_dispatch/journey/router.rb:49:in `block in serve'
/usr/local/bundle/gems/actionpack-6.0.3.1/lib/action_dispatch/journey/router.rb:32:in `each'
/usr/local/bundle/gems/actionpack-6.0.3.1/lib/action_dispatch/journey/router.rb:32:in `serve'
/usr/local/bundle/gems/actionpack-6.0.3.1/lib/action_dispatch/routing/route_set.rb:834:in `call'
/usr/local/bundle/gems/omniauth-1.9.1/lib/omniauth/strategy.rb:192:in `call!'
/usr/local/bundle/gems/omniauth-1.9.1/lib/omniauth/strategy.rb:169:in `call'
/usr/local/bundle/gems/omniauth-1.9.1/lib/omniauth/builder.rb:45:in `call'
/app/app/middlewares/rescue_from_invalid_authenticity_token.rb:8:in `call'
/usr/local/bundle/gems/rack-2.2.3/lib/rack/tempfile_reaper.rb:15:in `call'
/usr/local/bundle/gems/rack-2.2.3/lib/rack/etag.rb:27:in `call'
/usr/local/bundle/gems/rack-2.2.3/lib/rack/conditional_get.rb:27:in `call'
/usr/local/bundle/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'
/usr/local/bundle/gems/actionpack-6.0.3.1/lib/action_dispatch/http/content_security_policy.rb:18:in `call'
/usr/local/bundle/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:266:in `context'
/usr/local/bundle/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:260:in `call'
/usr/local/bundle/gems/actionpack-6.0.3.1/lib/action_dispatch/middleware/cookies.rb:648:in `call'
/usr/local/bundle/gems/actionpack-6.0.3.1/lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
/usr/local/bundle/gems/activesupport-6.0.3.1/lib/active_support/callbacks.rb:101:in `run_callbacks'
/usr/local/bundle/gems/actionpack-6.0.3.1/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
/usr/local/bundle/gems/actionpack-6.0.3.1/lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
/usr/local/bundle/gems/actionpack-6.0.3.1/lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
/usr/local/bundle/gems/actionpack-6.0.3.1/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
/usr/local/bundle/gems/railties-6.0.3.1/lib/rails/rack/logger.rb:37:in `call_app'
/usr/local/bundle/gems/railties-6.0.3.1/lib/rails/rack/logger.rb:26:in `block in call'
/usr/local/bundle/gems/activesupport-6.0.3.1/lib/active_support/tagged_logging.rb:80:in `block in tagged'
/usr/local/bundle/gems/activesupport-6.0.3.1/lib/active_support/tagged_logging.rb:28:in `tagged'
/usr/local/bundle/gems/activesupport-6.0.3.1/lib/active_support/tagged_logging.rb:80:in `tagged'
/usr/local/bundle/gems/railties-6.0.3.1/lib/rails/rack/logger.rb:26:in `call'
/usr/local/bundle/gems/actionpack-6.0.3.1/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
/usr/local/bundle/gems/rack-timeout-0.6.0/lib/rack/timeout/core.rb:151:in `block in call'
/usr/local/bundle/gems/rack-timeout-0.6.0/lib/rack/timeout/support/timeout.rb:19:in `timeout'
/usr/local/bundle/gems/rack-timeout-0.6.0/lib/rack/timeout/core.rb:150:in `call'
/usr/local/bundle/gems/actionpack-6.0.3.1/lib/action_dispatch/middleware/request_id.rb:27:in `call'
/usr/local/bundle/gems/rack-2.2.3/lib/rack/method_override.rb:24:in `call'
/usr/local/bundle/gems/rack-2.2.3/lib/rack/runtime.rb:22:in `call'
/usr/local/bundle/gems/activesupport-6.0.3.1/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
/usr/local/bundle/gems/actionpack-6.0.3.1/lib/action_dispatch/middleware/executor.rb:14:in `call'
/usr/local/bundle/gems/actionpack-6.0.3.1/lib/action_dispatch/middleware/static.rb:126:in `call'
/usr/local/bundle/gems/rack-2.2.3/lib/rack/sendfile.rb:110:in `call'
/usr/local/bundle/gems/actionpack-6.0.3.1/lib/action_dispatch/middleware/host_authorization.rb:76:in `call'
/usr/local/bundle/gems/sentry-raven-3.0.0/lib/raven/integrations/rack.rb:51:in `call'
/usr/local/bundle/gems/railties-6.0.3.1/lib/rails/engine.rb:527:in `call'
/usr/local/bundle/gems/puma-4.3.5/lib/puma/configuration.rb:228:in `call'
/usr/local/bundle/gems/puma-4.3.5/lib/puma/server.rb:713:in `handle_request'
/usr/local/bundle/gems/puma-4.3.5/lib/puma/server.rb:472:in `process_client'
/usr/local/bundle/gems/puma-4.3.5/lib/puma/server.rb:328:in `block in run'
/usr/local/bundle/gems/puma-4.3.5/lib/puma/thread_pool.rb:134:in `block in spawn_thread'
```

**Comment by MasayaAoyama** [comment]
再現動画
https://drive.google.com/file/d/1GrMkz-REQJjy_I09unhdKYvxmhz27Uk8/view?usp=sharing
